'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Cliente
    Public Property ClienteID As Integer
    Public Property NroDocumento As String
    Public Property NombreApelllido As String
    Public Property CiudadID As Nullable(Of Integer)
    Public Property Direccion As String
    Public Property Telefono As String
    Public Property EstaActivo As String

    Public Overridable Property Ciudad As Ciudad
    Public Overridable Property Mascota As ICollection(Of Mascota) = New HashSet(Of Mascota)

End Class
