'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Mascota
    Public Property MascotaID As Integer
    Public Property ClienteID As Integer
    Public Property Nombre As String
    Public Property RazaID As Integer
    Public Property FechaNacimiento As Date
    Public Property Sexo As String
    Public Property EspecieID As Nullable(Of Integer)
    Public Property EstaActivo As String

    Public Overridable Property Cliente As Cliente
    Public Overridable Property Especie As Especie
    Public Overridable Property Raza As Raza
    Public Overridable Property MascotaVacuna As ICollection(Of MascotaVacuna) = New HashSet(Of MascotaVacuna)

End Class
