'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class MascotaVacuna
    Public Property MascotaVacunaID As Integer
    Public Property MascotaID As Integer
    Public Property VacunaID As Integer
    Public Property FechaVacunacion As Date
    Public Property FechaProximaVacunacion As Nullable(Of Date)
    Public Property Costo As Nullable(Of Decimal)

    Public Overridable Property Mascota As Mascota
    Public Overridable Property Vacuna As Vacuna

End Class
