'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Vacuna
    Public Property VacunaID As Integer
    Public Property Descripcion As String
    Public Property PeriodicidadMes As Integer
    Public Property EstaActivo As String

    Public Overridable Property MascotaVacuna As ICollection(Of MascotaVacuna) = New HashSet(Of MascotaVacuna)

End Class
